<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>xpouyat</Authors>
    <Company>Microsoft</Company>
    <Description>A .NET client SDK for MediaKind MK.IO.</Description>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>2.2.0</Version>
    <RepositoryUrl>https://github.com/Epicode/emplo-mkio</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/Epicode/emplo-mkio/blob/main/README.md</PackageProjectUrl>
    <AssemblyVersion>2.2.0.0</AssemblyVersion>
    <FileVersion>2.2.0.0</FileVersion>
    <Title>A .NET client SDK for MediaKind MK.IO.</Title>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageIcon>mkio.png</PackageIcon>
    <!-- Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Recommended: Embed symbols containing Source Link in the main file (exe/dll) -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\mkio.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\SampleContentKeyPolicyOperations.md" Link="SampleContentKeyPolicyOperations.md" />
    <None Include="..\SampleFilterOperations.md" Link="SampleFilterOperations.md" />
    <None Include="..\SampleStorageOperations.md" Link="SampleStorageOperations.md" />
    <None Include="..\SampleTransformAndJobOperations.md" Link="SampleTransformAndJobOperations.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSubTypes" Version="2.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.2.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Icon\mkio.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="MK.IO.Tests" />
	  <!-- Make assembly usable for Moq, so Moq an other test code is able to instanciate objects of 'internal' classes -->
	  <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
		  <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
	  </AssemblyAttribute>
  </ItemGroup>
</Project>